// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXiT_PmB-ABa-oOqN6uE-10Ue4e9hNWUI',
    appId: '1:774921767039:web:252ea40170085c26dc574a',
    messagingSenderId: '774921767039',
    projectId: 'xsports-a951a',
    authDomain: 'xsports-a951a.firebaseapp.com',
    storageBucket: 'xsports-a951a.appspot.com',
    measurementId: 'G-T1RCR52D79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey:
        'AIzaSyBX3qlq6JKR36rX3syys784cDLzMS-6-tc', // existing API key is correct
    appId:
        '1:774921767039:android:766092a5aca98fa2dc574a', // new App ID from your details
    messagingSenderId: '774921767039', // stays the same
    projectId: 'xsports-a951a', // stays the same
    storageBucket: 'xsports-a951a.appspot.com', // stays the same
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBfE8-Uxv-1AgAXc68x8bBOGxdNIE65qzM', // existing API key is correct
    appId:
        '1:774921767039:ios:baa4d772b075a93adc574a', // new App ID from your details
    messagingSenderId: '774921767039', // stays the same
    projectId: 'xsports-a951a', // stays the same
    storageBucket: 'xsports-a951a.appspot.com', // stays the same
    iosBundleId: 'com.joka.XSports', // new bundle ID
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfE8-Uxv-1AgAXc68x8bBOGxdNIE65qzM',
    appId: '1:774921767039:ios:6fff7cd14340eaf3dc574a',
    messagingSenderId: '774921767039',
    projectId: 'xsports-a951a',
    storageBucket: 'xsports-a951a.appspot.com',
    iosBundleId: 'com.example.xSport.RunnerTests',
  );
}
