// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> en = {
  "welcome": "Welcome",
  "welcome_to_xsports_app": "Welcome to XSPORTS app",
  "personalize_your_experience": "Personalize your XSPORTS experience Access your favorite stadiums, find your ideal partners, manage your team and join the most important events",
  "create": "CREATE",
  "more_sign_in_options": "More sign in options:",
  "accepting_our": "By registering you are accepting our",
  "terms": "terms",
  "of_use_and": "of use and",
  "privacy_policy": "privacy policy",
  "sign_in": "SIGN IN",
  "more": "More",
  "sign_in_option": "sign in",
  "join": "JOIN",
  "create_your_id": "CREATE YOUR XSPORTS ID",
  "register_sub_title": "Save your preferences inside the app by creating a free XSPORT ID that gives you access to all the features and status of your events.",
  "first_name_and_last_name": "First name and last name",
  "mobile_number": "Mobile number",
  "username_or_email": "username or email",
  "forgot_your_password": "forgot your password?",
  "sign_in_to_xsports_with_your_id": "SIGN IN TO XSPORTS WITH YOUR ID",
  "options": "options",
  "competition_here": "Competition is here!",
  "add_friends_compete": "Add friends in your area to compete together",
  "search_academies": "Search for academies near you to turn your hobby into a profession",
  "post_match_ad": "Post your match advertisement to find an opponent",
  "browse_courts": "Browse Courts near you and book your next reservation",
  "friends_courts": "Courts frequented by your friends",
  "description": "Description",
  "follow": "Follow",
  "the_championships": "The Championships",
  "ongoing": "Ongoing",
  "upcoming": "Upcoming",
  "expired": "Expired",
  "champ_name": "Championship Name",
  "organizers": "Organizers",
  "court_name": "Court Name",
  "academy": "The Academy",
  "start": "Start",
  "end": "End",
  "joining_unavailable": "Joining the championship is not available",
  "show_more": "Show More",
  "community": "Community",
  "you": "You",
  "username": "Username",
  "post_desc": "Description of the post written by the user",
  "search": "Search",
  "people": "People",
  "courts": "Courts",
  "academies": "Academies",
  "enter_search": "Enter what you are looking for",
  "player_name": "Player Name",
  "personal_info": "Personal Information",
  "people_may_know": "People you may know",
  "unfollow": "Unfollow",
  "personal_account": "Personal Account",
  "premium_account": "Premium Account",
  "location": "Location",
  "followers": "Followers",
  "following": "Following",
  "posts_archive": "Posts Archive",
  "played_matches": "Played Matches Archive",
  "active_matches": "Active Matches Archive",
  "no_matches": "No matches yet",
  "no_posts": "No posts yet",
  "remove_sport": "Remove Sport",
  "level": "Level",
  "match_count": "Number of Matches",
  "new_challenge": "Search for a New Challenge",
  "book_match": "Book a New Match or Find a New Opponent",
  "beginner": "Beginner",
  "amateur": "Amateur",
  "experienced": "Experienced",
  "player_prefs": "Player Preferences",
  "preferred_foot": "Preferred Foot",
  "not_specified": "Not Specified",
  "left": "Left",
  "right": "Right",
  "preferred_pos": "Preferred Position",
  "goalkeeper": "Goalkeeper",
  "defender": "Defender",
  "midfielder": "Midfielder",
  "forward": "Forward",
  "preferred_time": "Preferred Time to Play",
  "morning": "Morning",
  "afternoon": "Afternoon",
  "evening": "Evening",
  "create_community": "Create Your Mini Community",
  "create_group": "Create a group of your friends who are eager for competition",
  "new_group": "New Group",
  "play": "Play",
  "x_sports_champs": "X Sports Championships",
  "check_champs": "Check out the championships organized by X Sports",
  "friendly_matches": "Friendly Matches",
  "play_friendly": "Play friendly matches near you",
  "comp_matches": "Competitive Matches",
  "play_comp": "Play competitive matches nearby and earn more points",
  "championships": "Championships",
  "view_champs": "View the results of ongoing championships and join upcoming championships",
  "leagues": "Leagues",
  "view_leagues": "View the results of ongoing leagues and join upcoming leagues",
  "join_champs": "Join one of the upcoming championships and increase your experience",
  "join_available": "Joining the championship is available",
  "participate_info": "Participate Information",
  "participate_avail": "Participate is Available",
  "participation_fee": "Participation Price",
  "champ_level": "Championship Level",
  "intermediate": "Intermediate",
  "participants": "Participants",
  "champ_prizes": "Championship Prizes",
  "show_results": "Show Results",
  "ranking": "Ranking",
  "group_1": "Group 1",
  "group_2": "Group 2",
  "group_3": "Group 3",
  "played": "Played",
  "won": "Won",
  "lost": "Lost",
  "matches": "Matches",
  "first_week": "First Week",
  "finished": "Finished",
  "champ_results": "Championship Results",
  "book_reservation": "Book a Reservation",
  "courts_nearby": "Courts Near You",
  "new_post": "New Post",
  "book_court": "Booking a Court",
  "start_match": "Start a Match",
  "login": "Login",
  "phone": "Phone",
  "email": "Email",
  "password": "Password",
  "login_fb": "Login with Facebook Account",
  "login_google": "Login with Google Account",
  "no_account": "Don't have an account! Sign up now",
  "create_account": "Create Account",
  "full_name": "Full Name",
  "confirm_password": "Confirm Password",
  "enable_location": "Enable Location",
  "phone_number": "Phone Number",
  "agree_terms": "I agree to the Terms of Use and Privacy Policy",
  "welcome_x_sports": "Welcome",
  "complete_info": "Complete your personal information for the best experience in X Sports",
  "choose_picture": "Choose a Profile Picture",
  "choose_sport": "Which sport would you prefer to start with",
  "add_sports_later": "You can add more sports later",
  "tennis": "Tennis",
  "padel": "Padel",
  "football": "Football",
  "basketball": "Basketball",
  "golf": "Golf",
  "game_1": "Game 1",
  "start_now": "Start Now",
  "verify_account": "Account Verifying",
  "enter_code": "Enter the Confirmation code",
  "enter_email_code": "Enter the Confirmation code that we sent to your email",
  "resend": "Resend",
  "about": "About",
  "academy_desc": "Text representing a description of the academy, its facilities, services, training systems, and everything that may interest the client",
  "natural_grass": "Natural Grass",
  "flexible_hours": "Flexible Hours",
  "medical_care": "Medical Care",
  "free_transport": "Free Transportation",
  "fee_range": "Participation start from 15 to 45 per month",
  "training_courses": "Training courses",
  "watch_video": "Watch Video",
  "choose_course": "Choose a training course that suits you",
  "under_7": "Under 7 Years Old",
  "course_name": "Course Name",
  "course_desc": "Brief Description of the Course",
  "males": "Males",
  "details": "Details",
  "for_you": "For You",
  "for_family": "For a Family Member",
  "age": "Age",
  "gender": "Gender",
  "residence": "Residence",
  "next": "Next",
  "select_course": "Select the Training course",
  "payment_method": "Preferred Payment Method",
  "card_number": "Card Number",
  "save_payment": "Save information as a preferred payment method",
  "simplify_payments": "Activating this option will simplify payment procedures in future bookings",
  "application_success": "Your application has been successfully submitted. You will receive a response from the academy if registration is completed within 48 hours",
  "okay": "Okay",
  "settings": "Settings",
  "edit_profile": "Edit Profile",
  "payment_info": "Payment Information",
  "archive": "Archive",
  "activities": "Activities",
  "privacy": "Privacy",
  "upgrade_premium": "Upgrade to Premium",
  "add_payment_method": "Add Payment Method",
  "edit": "Edit",
  "payment_history": "Payment History",
  "view_all": "View All",
  "reserved_court": "Reserved Court Name",
  "date_time": "Date and Time",
  "amount_paid": "Amount Paid",
  "user_privacy": "User Privacy",
  "card_info": "Personal Card Information",
  "played_matches_archive": "Archive of Played Matches",
  "academies_archive": "Academies Archive",
  "stories_archive": "Stories Archive",
  "community_archive": "Community and Posts Archive",
  "champs_archive": "Championships Archive",
  "review_champs": "You can review the championships you have participated in",
  "oldest": "Oldest",
  "latest": "Latest",
  "not_started": "Not Started Yet",
  "review_academies": "You can review your academy subscriptions",
  "likes": "Likes",
  "comments": "Comments",
  "reservations": "Reservations",
  "filter_archive": "Filter Archive",
  "date": "Date",
  "all": "All",
  "last_year": "Last Year",
  "last_month": "Last Month",
  "last_week": "Last Week",
  "apply_changes": "Apply Changes",
  "comments_archive": "Comments Archive",
  "text_above_post": "Text appears above the post",
  "partial_comment": "The comment appears, and if it is long, part of it appears",
  "search_history": "Search History",
  "search_text": "Search text is written here",
  "settings_privacy": "Settings and Privacy",
  "language": "Language"
};
static const Map<String,dynamic> ar = {
  "welcome": "أهلاً",
  "welcome_to_xsports_app": "مرحبًا بك في تطبيق XSPORTS",
  "personalize_your_experience": "خصص تجربة XSPORTS الخاصة بك. يمكنك الوصول إلى ملاعبك المفضلة والعثور على شركائك المثاليين وإدارة فريقك والانضمام إلى أهم الأحداث",
  "create": "إنشاء",
  "more_sign_in_options": "المزيد من خيارات تسجيل الدخول:",
  "accepting_our": "بتسجيلك فإنك تقبل موقعنا",
  "terms": "الشروط",
  "of_use_and": "الاستخدام و",
  "privacy_policy": "سياسة الخصوصية",
  "sign_in": "تسجيل الدخول",
  "more": "اكثر",
  "sign_in_option": "تسجيل الدخول",
  "create_your_id": "إنشاء معرف XSPORTS الخاص بك",
  "register_sub_title": "احفظ تفضيلاتك داخل التطبيق عن طريق إنشاء معرف XSPORT مجاني يتيح لك الوصول إلى جميع الميزات وحالة الأحداث الخاصة بك.",
  "first_name_and_last_name": "الاسم الأول واسم العائلة",
  "mobile_number": "رقم الجوال",
  "username_or_email": "اسم المستخدم أو البريد الإلكتروني",
  "forgot_your_password": "؟نسيت كلمة المرور الخاصة بك",
  "sign_in_to_xsports_with_your_id": "سجل الدخول إلى XSPORTS باستخدام هويتك",
  "options": "خيارات",
  "competition_here": "المنافسة أقرب إليك",
  "add_friends_compete": "إضافة أصدقاء في منطقتك لتتنافسوا سوياً",
  "search_academies": "ابحث عن أكاديميات بقربك لتحول هوايتك إلى احتراف",
  "post_match_ad": "انشر إعلان مباراتك لتبحث عن خصم لك",
  "browse_courts": "استعرض الملاعب بالقرب منك ونظم حجزك القادم",
  "friends_courts": "ملاعب يرتادها أصدقائك",
  "description": "وصف",
  "follow": "تابع",
  "the_championships": "The Championships",
  "ongoing": "مستمرة",
  "upcoming": "قادمة",
  "expired": "منتهية",
  "champ_name": "اسم البطولة",
  "organizers": "الجهة المنظمة",
  "court_name": "اسم الملعب",
  "academy": "الأكاديمية",
  "start": "البدء",
  "end": "الانتهاء",
  "joining_unavailable": "الانضمام للبطولة غير متاح",
  "show_more": "عرض المزيد",
  "community": "المجتمع",
  "you": "أنت",
  "username": "اسم المستخدم",
  "post_desc": "وصف البوست المكتوب من قبل المستخدم",
  "search": "البحث",
  "people": "أشخاص",
  "courts": "ملاعب",
  "academies": "أكاديميات",
  "enter_search": "أدخل ما تبحث عنه",
  "player_name": "اسم اللاعب",
  "personal_info": "معلومات شخصية",
  "people_may_know": "أشخاص قد تعرفهم",
  "unfollow": "إلغاء المتابعة",
  "personal_account": "الحساب الشخصي",
  "premium_account": "حساب بريميوم",
  "location": "الموقع الجغرافي",
  "edit_profile": "تعديل الملف الشخصي",
  "followers": "متابعون",
  "following": "متابعين",
  "posts_archive": "أرشيف المنشورات",
  "played_matches": "أرشيف المباريات الملعوبة",
  "active_matches": "أرشيف المباريات النشطة",
  "no_matches": "لا يوجد مباريات بعد",
  "no_posts": "لا يوجد منشورات بعد",
  "activities": "الأنشطة",
  "remove_sport": "إزالة اللعبة",
  "football": "كرة القدم",
  "level": "المستوى",
  "match_count": "عدد المباريات",
  "new_challenge": "ابحث عن تحدي جديد",
  "start_match": "ابدأ مباراة جديدة",
  "book_match": "احجز مباراة جديدة أو ابحث عن خصم جديد",
  "beginner": "مبتدئ",
  "amateur": "هاوٍ",
  "experienced": "متمرس",
  "player_prefs": "تفضيلات اللاعب",
  "preferred_foot": "القدم المفضلة",
  "not_specified": "غير مخصص",
  "left": "يسار",
  "right": "يمين",
  "preferred_pos": "المركز المفضل",
  "goalkeeper": "حارس مرمى",
  "defender": "مدافع",
  "midfielder": "خط وسط",
  "forward": "مهاجم",
  "preferred_time": "الوقت المفضل للعب",
  "morning": "صباحاً",
  "afternoon": "ظهراً",
  "evening": "مساءاً",
  "create_community": "أنشئ مجتمعك المصغر",
  "create_group": "قم بإنشاء مجموعة من أصدقائك اللاعبين المتعطشين للمنافسة",
  "new_group": "مجموعة جديدة",
  "play": "العب",
  "x_sports_champs": "بطولات X Sports",
  "check_champs": "اطلع على البطولات المنظمة من قِبل X Sports",
  "friendly_matches": "مباريات ودية",
  "play_friendly": "العب مباريات ودية قريبة منك",
  "comp_matches": "المباريات التنافسية",
  "play_comp": "العب مباريات تنافسية قريبة واكسب نقاط أكثر",
  "championships": "البطولات",
  "view_champs": "اطلع على نتائج البطولات المُقامة واشترك في بطولات قادمة",
  "leagues": "الدوريات",
  "view_leagues": "اطلع على نتائج الدوريات المُقامة واشترك في دوريات قادمة",
  "join_champs": "اشترك في أحد البطولات القادمة وزد من خبرتك",
  "join_available": "الانضمام للبطولة متاح",
  "participate_info": "معلومات الاشتراك",
  "participate_avail": "التسجيل متاح",
  "participation_fee": "رسم الاشتراك",
  "champ_level": "مستوى البطولة",
  "intermediate": "متوسط",
  "participants": "المشاركين",
  "champ_prizes": "جوائز البطولة",
  "show_results": "عرض النتائج",
  "ranking": "الترتيب",
  "group_1": "المجموعة الأولى",
  "group_2": "المجموعة الثانية",
  "group_3": "المجموعة الثالثة",
  "played": "لعب",
  "won": "فاز",
  "lost": "خسر",
  "matches": "المباريات",
  "first_week": "الأسبوع الأول",
  "finished": "انتهت",
  "champ_results": "نتائج البطولة",
  "book_reservation": "نظّم حجز",
  "courts_nearby": "الملاعب القريبة منك",
  "new_post": "منشور جديد",
  "book_court": "حجز ملعب",
  "login": "تسجيل الدخول",
  "phone": "الرقم",
  "email": "البريد الإلكتروني",
  "password": "كلمة المرور",
  "login_fb": "تسجيل الدخول عبر الفيسبوك",
  "login_google": "تسجيل الدخول عبر جوجل",
  "no_account": "ليس لديك حساب! سجل الآن",
  "create_account": "إنشاء حساب",
  "full_name": "الاسم الكامل",
  "confirm_password": "تأكيد كلمة المرور",
  "enable_location": "تفعيل الموقع الجغرافي",
  "phone_number": "رقم الموبايل",
  "agree_terms": "أوافق على شروط الاستخدام والخصوصية",
  "welcome_x_sports": "أهلاً بك",
  "complete_info": "قم بإكمال معلوماتك الشخصية كي تحقق أفضل تجربة في X Sports",
  "choose_picture": "اختر صورة شخصية",
  "choose_sport": "أي رياضة تفضّل أن تبدأ بها",
  "add_sports_later": "يمكنك إضافة المزيد من النشاطات لاحقاً",
  "tennis": "تنس",
  "padel": "بادل",
  "basketball": "كرة سلة",
  "golf": "غولف",
  "game_1": "لعبة1",
  "start_now": "ابدا الآن",
  "verify_account": "تأكيد الحساب",
  "enter_code": "قم بإدخال رمز التأكيد",
  "enter_email_code": "أدخل رمز التأكيد الذي قمنا بإرساله إلى بريدك الإلكتروني",
  "resend": "إرسال مرة أخرى",
  "about": "حول",
  "academy_desc": "نص يمثل وصف عن الأكاديمية ومرافقها وخدماتها والأنظمة التدريبية المتبعة وكل ما يمكن أن يهمن العميل",
  "natural_grass": "عشب طبيعي",
  "flexible_hours": "أوقات مرنة",
  "medical_care": "عناية طبية",
  "free_transport": "مواصلات مؤمنة",
  "fee_range": "الاشتراك يبدأ من 15 إلى 45 شهرياً",
  "training_courses": "برمج التدريب",
  "watch_video": "مشاهدة الفيديو",
  "choose_course": "اختر برنامجاً تدريبياً يناسبك",
  "under_7": "تحت 7 سنين",
  "course_name": "اسم الكورس",
  "course_desc": "وصف بسيط عن الكورس",
  "males": "ذكور",
  "details": "تفاصيل",
  "for_you": "لك",
  "for_family": "لأحد أفراد العائلة",
  "age": "تحديد العمر",
  "gender": "الجنس",
  "residence": "مكان الإقامة",
  "next": "التالي",
  "select_course": "اختر البرنامج التدريبي المناسب",
  "payment_method": "وسيلة الدفع المفضلة",
  "card_number": "رقم البطاقة",
  "save_payment": "حفظ المعلومات كوسيلة دفع مفضلة",
  "simplify_payments": "سيسهل عليك تفعيل هذا الخيار إجراءات الدفع في الحجوزات القادمة",
  "application_success": "تم بتقديم الطلب بنجاح سيصلك الرد من الأكاديمية في حال إتمام التسجيل خلال 48 ساعة",
  "okay": "حسناً",
  "settings": "الإعدادات",
  "payment_info": "معلومات الدفع",
  "archive": "الأرشيف",
  "upgrade_premium": "ترقية إلى بريميوم",
  "add_payment_method": "إضافة وسيلة دفع",
  "edit": "تعديل",
  "payment_history": "تاريخ المدفوعات",
  "view_all": "عرض الكل",
  "reserved_court": "اسم الملعب المحجوز",
  "date_time": "التاريخ باليوم والساعة",
  "amount_paid": "المبلغ المدفوع",
  "user_privacy": "خصوصية المستخدم",
  "card_info": "معلومات البطاقة الشخصية",
  "played_matches_archive": "أرشيف المباريات الملعوبة",
  "academies_archive": "أرشيف الأكاديميات",
  "stories_archive": "أرشيف القصص",
  "community_archive": "أرشيف المجتمع والمنشورات",
  "champs_archive": "أرشيف البطولات",
  "review_champs": "يمكنك مراجعة البطولات التي قمت بالاشتراك بها",
  "oldest": "الأٌقدم",
  "latest": "الأحدث",
  "not_started": "لم تبدأ بعد",
  "review_academies": "يمكنك مراجعة اشتراكاتك بالأكاديميات",
  "likes": "تسجيلات الإعجاب",
  "comments": "التعليقات",
  "reservations": "الحجوزات",
  "filter_archive": "فلترة الأرشيف",
  "date": "التاريخ",
  "all": "الكل",
  "last_year": "اخر سنة",
  "last_month": "اخر شهر",
  "last_week": "أخر أسبوع",
  "apply_changes": "تطبيق التغييرات",
  "comments_archive": "أرشيف التعليقات",
  "text_above_post": "يظهر النص فوق البوست",
  "partial_comment": "يظهر التعليق، واذا كان طويلاً يظهر جزء منه",
  "search_history": "سجل البحث",
  "search_text": "نص البحث يكتب هنا",
  "settings_privacy": "الاعدادات والخصوصية",
  "language": "اللغة",
  "privacy": "الخصوصية"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"en": en, "ar": ar};
}
